import { app, BrowserWindow, session } from 'electron';
import { hooks } from './hooks';
import { createReadStream } from 'fs';
import * as fs from 'fs/promises';
import * as path from 'path';
import unzipper from 'unzipper';
// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  // eslint-disable-line global-require
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    titleBarStyle: 'hidden',
    titleBarOverlay: {
      color: '#eee',
    },
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();

  session.defaultSession.webRequest.onBeforeSendHeaders(
    { urls: ['https://m5.qq.com/*', 'https://imtt.dd.qq.com/*'] },
    (details, callback) => {
      details.requestHeaders[
        'User-Agent'
      ] = `Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36 QBCore/3.43.815.400 QQBrowser/9.0.2524.400`;
      callback({ requestHeaders: details.requestHeaders });
    }
  );

  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: Object.assign(details.responseHeaders, {
        'Content-Security-Policy': ["'default-src 'self'", 'img-src *'],
      }),
    });
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.whenReady().then(() => {
  hooks(app);

  const downloadPathDataFile = path.resolve(
    app.getPath('userData'),
    'download-path'
  );
  fs.readFile(downloadPathDataFile, 'utf8').catch(() => {
    fs.writeFile(downloadPathDataFile, app.getPath('downloads'), 'utf8');
  });

  createReadStream(
    path.resolve('resources', 'platform-tools-latest-windows.zip')
  ).pipe(unzipper.Extract({ path: app.getPath('userData') }));
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
